# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

jobs:
  include:
  - r: release
    os: linux
  - r: release
    os: osx
    osx_image: xcode12.5
  - r: devel
    os: linux
  - r: oldrel
    os: linux
  - r: oldrel
    os: osx
    osx_image: xcode11.3
