# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
dist: trusty

jobs:
  include:
  - r: release
    os: linux
  - r: release
    os: osx
  - r: devel
    os: linux

osx_image: xcode10.2

after_success:
  - if [ "$TRAVIS_OS_NAME" != "osx" ]; then travis_wait 30 Rscript -e 'covr::codecov()'; fi
