# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7

script:
  - export CC=gcc-7
  - export CXX=g++-7

r_packages:
  - covr

r:
  - release
  - oldrel
  - devel

os:
  - linux

after_success:
  - Rscript -e 'library(covr); codecov()'
