# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
dist: trusty

r_github_packages:
  - r-lib/covr

r:
  - release
  - oldrel

os:
  - linux
  - osx

osx_image: xcode8

after_success:
  - travis_wait 20 Rscript -e 'covr::codecov()'
